### ISSUE TITLE
libotp not imported despite self-built libotp.pyd being present within the OpenRTM folder

### ISSUE THREAD

**Issue by Rinfinity1** [OpenToontownTools/OpenRTM#3]
```
Traceback (most recent call last):
  File "D:\Panda3D-1.10.14-x64\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Panda3D-1.10.14-x64\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\OpenRTM\rtm.py", line 78, in <module>
    RTMBase().run()
  File "F:\OpenRTM\rtm.py", line 68, in __init__
    builtins.__dict__.update(__import__('libotp', fromlist=['*']).__dict__)
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by drewc5131** [comment]
sounds like you didn't build the pyd file yourself against the version of panda you're using and instead just dropped a pre built one into the folder. This is a user error, this issue is closed.

**Comment by Rinfinity1** [comment]
> sounds like you didn't build the pyd file yourself against the version of panda you're using and instead just dropped a pre built one into the folder. This is a user error, this issue is closed.

I did build it myself, I tried building it using different versions of panda `Panda3D-1.10.14-x64` and `1.11.0-x64` 
It keeps resulting in that error.
![image](https://github.com/OpenToontownTools/OpenRTM/assets/58800515/e4b014f3-53ad-417b-810b-f9f8fd182d1d)
![image](https://github.com/OpenToontownTools/OpenRTM/assets/58800515/5dcc7111-937f-4385-8b77-48c146e9820d)
I've never done this before, I'm not sure what I'm doing wrong. I would greatly appreciate your help.

**Comment by Rinfinity1** [comment]
Rebuilding it doesn't appear to solve the error, not sure what I'm doing wrong.

```
Traceback (most recent call last):
  File "C:\Panda3D-TTRMDev-1.11.0-x64\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Panda3D-TTRMDev-1.11.0-x64\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\OpenRTM\rtm.py", line 78, in <module>
    RTMBase().run()
  File "F:\OpenRTM\rtm.py", line 72, in __init__
    from toontown.toon import RobotToonManager
  File "F:\OpenRTM\toontown\toon\RobotToonManager.py", line 7, in <module>
    from .RobotToon import *
  File "F:\OpenRTM\toontown\toon\RobotToon.py", line 1, in <module>
    from . import Toon
  File "F:\OpenRTM\toontown\toon\Toon.py", line 8, in <module>
    from .ToonHead import *
  File "F:\OpenRTM\toontown\toon\ToonHead.py", line 13, in <module>
    from toontown.toonbase import ToontownGlobals
  File "F:\OpenRTM\toontown\toonbase\ToontownGlobals.py", line 8, in <module>
    from direct.showbase.PythonUtil import Enum, invertDict
ImportError: cannot import name 'Enum'
```

got a different error this time. This error is earlier in the script so I probably just broke it more xD.

**Comment by drewc5131** [comment]
This program has not been updated in 4 years, you're using a build of panda from just a few months ago, you will need a build of panda that was built around this time. You will have to clone the panda3d repo from a commit around this time

I'd also like to mention this program is barely functional so i dont even see why you'd use it right now.

**Comment by Rinfinity1** [comment]
> This program has not been updated in 4 years, you're using a build of panda from just a few months ago, you will need a build of panda that was built around this time. You will have to clone the panda3d repo from a commit around this time
> 
> I'd also like to mention this program is barely functional so i dont even see why you'd use it right now.

I didn't know any of this apart from the 4 years ago part.
